USE sakila;
-- Write SQL queries to perform the following tasks using the Sakila database:
	-- List the number of films per category.
SELECT c.category_id, count(f.film_id) 
FROM film AS f
JOIN film_category AS c ON f.film_id = c.film_id
GROUP BY c.category_id; 

	-- Retrieve the store ID, city, and country for each store.
SELECT s.store_id, ci.city, co.country
FROM store AS s
JOIN address AS a ON s.address_id = a.address_id
JOIN city AS ci ON a.city_id = ci.city_id
JOIN country AS co ON ci.country_id = co.country_id;

	-- Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM store AS s
JOIN staff AS st ON s.store_id = st.store_id
JOIN payment AS p ON st.staff_id = p.staff_id
GROUP BY s.store_id;

	-- Determine the average running time of films for each category.
   SELECT c.name, avg(f.length) AS AVG_length
   FROM category as c
   JOIN film_category as fc ON c.category_id = fc.category_id
   JOIN film as f ON fc.film_id = f.film_id
   GROUP BY c.name;
   
   